#ifndef WASM_SIMD_INTRINSICS_WASM2C_H_GENERATED_
#define WASM_SIMD_INTRINSICS_WASM2C_H_GENERATED_

/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
// copied from wasm_simd128.h header 
typedef int32_t v128_t __attribute__((__vector_size__(16), __aligned__(16)));

#ifndef WASM_DONT_EXPORT_FUNCS
# if defined(_WIN32)
#   define FUNC_EXPORT __declspec(dllexport)
# else
#   define FUNC_EXPORT
# endif
#else
# define FUNC_EXPORT
#endif

FUNC_EXPORT wasm2c_sandbox_funcs_t WASM_RT_ADD_PREFIX(get_wasm2c_sandbox_info)();

struct wasm2c_sandbox_t;
typedef struct wasm2c_sandbox_t wasm2c_sandbox_t;

/* import: 'wasi_snapshot_preview1' 'args_get' */
extern u32 Z_wasi_snapshot_preview1Z_args_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'args_sizes_get' */
extern u32 Z_wasi_snapshot_preview1Z_args_sizes_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'environ_get' */
extern u32 Z_wasi_snapshot_preview1Z_environ_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'environ_sizes_get' */
extern u32 Z_wasi_snapshot_preview1Z_environ_sizes_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'clock_res_get' */
extern u32 Z_wasi_snapshot_preview1Z_clock_res_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'clock_time_get' */
extern u32 Z_wasi_snapshot_preview1Z_clock_time_getZ_iiji(void*, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_advise' */
extern u32 Z_wasi_snapshot_preview1Z_fd_adviseZ_iijji(void*, u32, u64, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_allocate' */
extern u32 Z_wasi_snapshot_preview1Z_fd_allocateZ_iijj(void*, u32, u64, u64);
/* import: 'wasi_snapshot_preview1' 'fd_close' */
extern u32 Z_wasi_snapshot_preview1Z_fd_closeZ_ii(void*, u32);
/* import: 'wasi_snapshot_preview1' 'fd_datasync' */
extern u32 Z_wasi_snapshot_preview1Z_fd_datasyncZ_ii(void*, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_get' */
extern u32 Z_wasi_snapshot_preview1Z_fd_fdstat_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_set_flags' */
extern u32 Z_wasi_snapshot_preview1Z_fd_fdstat_set_flagsZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_set_rights' */
extern u32 Z_wasi_snapshot_preview1Z_fd_fdstat_set_rightsZ_iijj(void*, u32, u64, u64);
/* import: 'wasi_snapshot_preview1' 'fd_filestat_get' */
extern u32 Z_wasi_snapshot_preview1Z_fd_filestat_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_filestat_set_size' */
extern u32 Z_wasi_snapshot_preview1Z_fd_filestat_set_sizeZ_iij(void*, u32, u64);
/* import: 'wasi_snapshot_preview1' 'fd_filestat_set_times' */
extern u32 Z_wasi_snapshot_preview1Z_fd_filestat_set_timesZ_iijji(void*, u32, u64, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_pread' */
extern u32 Z_wasi_snapshot_preview1Z_fd_preadZ_iiiiji(void*, u32, u32, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_prestat_get' */
extern u32 Z_wasi_snapshot_preview1Z_fd_prestat_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_prestat_dir_name' */
extern u32 Z_wasi_snapshot_preview1Z_fd_prestat_dir_nameZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_pwrite' */
extern u32 Z_wasi_snapshot_preview1Z_fd_pwriteZ_iiiiji(void*, u32, u32, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_read' */
extern u32 Z_wasi_snapshot_preview1Z_fd_readZ_iiiii(void*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_readdir' */
extern u32 Z_wasi_snapshot_preview1Z_fd_readdirZ_iiiiji(void*, u32, u32, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'fd_renumber' */
extern u32 Z_wasi_snapshot_preview1Z_fd_renumberZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_seek' */
extern u32 Z_wasi_snapshot_preview1Z_fd_seekZ_iijii(void*, u32, u64, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_sync' */
extern u32 Z_wasi_snapshot_preview1Z_fd_syncZ_ii(void*, u32);
/* import: 'wasi_snapshot_preview1' 'fd_tell' */
extern u32 Z_wasi_snapshot_preview1Z_fd_tellZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_write' */
extern u32 Z_wasi_snapshot_preview1Z_fd_writeZ_iiiii(void*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_create_directory' */
extern u32 Z_wasi_snapshot_preview1Z_path_create_directoryZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_filestat_get' */
extern u32 Z_wasi_snapshot_preview1Z_path_filestat_getZ_iiiiii(void*, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_filestat_set_times' */
extern u32 Z_wasi_snapshot_preview1Z_path_filestat_set_timesZ_iiiiijji(void*, u32, u32, u32, u32, u64, u64, u32);
/* import: 'wasi_snapshot_preview1' 'path_link' */
extern u32 Z_wasi_snapshot_preview1Z_path_linkZ_iiiiiiii(void*, u32, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_open' */
extern u32 Z_wasi_snapshot_preview1Z_path_openZ_iiiiiijjii(void*, u32, u32, u32, u32, u32, u64, u64, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_readlink' */
extern u32 Z_wasi_snapshot_preview1Z_path_readlinkZ_iiiiiii(void*, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_remove_directory' */
extern u32 Z_wasi_snapshot_preview1Z_path_remove_directoryZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_rename' */
extern u32 Z_wasi_snapshot_preview1Z_path_renameZ_iiiiiii(void*, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_symlink' */
extern u32 Z_wasi_snapshot_preview1Z_path_symlinkZ_iiiiii(void*, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_unlink_file' */
extern u32 Z_wasi_snapshot_preview1Z_path_unlink_fileZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'poll_oneoff' */
extern u32 Z_wasi_snapshot_preview1Z_poll_oneoffZ_iiiii(void*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'proc_exit' */
extern void Z_wasi_snapshot_preview1Z_proc_exitZ_vi(void*, u32);
/* import: 'wasi_snapshot_preview1' 'proc_raise' */
extern u32 Z_wasi_snapshot_preview1Z_proc_raiseZ_ii(void*, u32);
/* import: 'wasi_snapshot_preview1' 'sched_yield' */
extern u32 Z_wasi_snapshot_preview1Z_sched_yieldZ_iv(void*);
/* import: 'wasi_snapshot_preview1' 'random_get' */
extern u32 Z_wasi_snapshot_preview1Z_random_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'sock_recv' */
extern u32 Z_wasi_snapshot_preview1Z_sock_recvZ_iiiiiii(void*, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'sock_send' */
extern u32 Z_wasi_snapshot_preview1Z_sock_sendZ_iiiiii(void*, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'sock_shutdown' */
extern u32 Z_wasi_snapshot_preview1Z_sock_shutdownZ_iii(void*, u32, u32);

FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c___wasm_call_ctors)(wasm2c_sandbox_t* const);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c__start)(wasm2c_sandbox_t* const);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_multiply_arrays)(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_add_arrays)(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_main)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_args_get)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_args_sizes_get)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_environ_get)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_environ_sizes_get)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_clock_res_get)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_clock_time_get)(wasm2c_sandbox_t* const, u32, u64, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_advise)(wasm2c_sandbox_t* const, u32, u64, u64, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_allocate)(wasm2c_sandbox_t* const, u32, u64, u64);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_close)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_datasync)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_fdstat_get)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_fdstat_set_flags)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_fdstat_set_rights)(wasm2c_sandbox_t* const, u32, u64, u64);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_filestat_get)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_filestat_set_size)(wasm2c_sandbox_t* const, u32, u64);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_filestat_set_times)(wasm2c_sandbox_t* const, u32, u64, u64, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_pread)(wasm2c_sandbox_t* const, u32, u32, u32, u64, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_prestat_get)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_prestat_dir_name)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_pwrite)(wasm2c_sandbox_t* const, u32, u32, u32, u64, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_read)(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_readdir)(wasm2c_sandbox_t* const, u32, u32, u32, u64, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_renumber)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_seek)(wasm2c_sandbox_t* const, u32, u64, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_sync)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_tell)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_fd_write)(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_path_create_directory)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_path_filestat_get)(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_path_filestat_set_times)(wasm2c_sandbox_t* const, u32, u32, u32, u64, u64, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_path_link)(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_path_open)(wasm2c_sandbox_t* const, u32, u32, u32, u32, u64, u64, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_path_readlink)(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_path_remove_directory)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_path_rename)(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_path_symlink)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_path_unlink_file)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_poll_oneoff)(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c___wasi_proc_exit)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_proc_raise)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_sched_yield)(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_random_get)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_sock_recv)(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_sock_send)(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___wasi_sock_shutdown)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_sbrk)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_malloc)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_dlmalloc)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_free)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_dlfree)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_calloc)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_realloc)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_dispose_chunk)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_posix_memalign)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_internal_memalign)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_aligned_alloc)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_malloc_usable_size)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c__Exit)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___main_void)(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___original_main)(wasm2c_sandbox_t* const);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_abort)(wasm2c_sandbox_t* const);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_dummy)(wasm2c_sandbox_t* const);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c___wasm_call_dtors)(wasm2c_sandbox_t* const);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_exit)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_printf)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_close)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___stdio_close)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u64 WASM_RT_ADD_PREFIX(w2c___lseek)(wasm2c_sandbox_t* const, u32, u64, u32);
FUNC_EXPORT u64 WASM_RT_ADD_PREFIX(w2c___stdio_seek)(wasm2c_sandbox_t* const, u32, u64, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_writev)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___stdio_write)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___isatty)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___stdout_write)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___ofl_lock)(wasm2c_sandbox_t* const);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c___ofl_unlock)(wasm2c_sandbox_t* const);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c___stdio_exit)(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___towrite)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c___towrite_needs_stdio_exit)(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___fwritex)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_fwrite)(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___strerror_l)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_strerror)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_fputs)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_vfprintf)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_printf_core)(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_pop_arg)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_pad)(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT void WASM_RT_ADD_PREFIX(w2c_long_double_not_supported)(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_strlen)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_memcpy)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_memset)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_strnlen)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_memchr)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_dummy_1)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___lctrans)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c___lctrans_cur)(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_wctomb)(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 WASM_RT_ADD_PREFIX(w2c_wcrtomb)(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT f64 WASM_RT_ADD_PREFIX(w2c_frexp)(wasm2c_sandbox_t* const, f64, u32);

#ifdef __cplusplus
}
#endif

#endif  /* WASM_SIMD_INTRINSICS_WASM2C_H_GENERATED_ */
